// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3BX90qcm7horfbPIowt8gusovejjKxkU',
    appId: '1:811204575228:web:7d13a5e19b169cfc533c79',
    messagingSenderId: '811204575228',
    projectId: 'myapp-366c1',
    authDomain: 'myapp-366c1.firebaseapp.com',
    storageBucket: 'myapp-366c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQMDmnkiDKl9jeeBKOGkgLqoeejzGO6LM',
    appId: '1:811204575228:android:ebdb5540da6efc66533c79',
    messagingSenderId: '811204575228',
    projectId: 'myapp-366c1',
    storageBucket: 'myapp-366c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKwZPq0rdwpbljnKAs6B0QGlsas0EBG1A',
    appId: '1:811204575228:ios:a0991f5a297c27e2533c79',
    messagingSenderId: '811204575228',
    projectId: 'myapp-366c1',
    storageBucket: 'myapp-366c1.appspot.com',
    iosClientId: '811204575228-nijh99ejuobltsihnfk8d0hni4v70ndn.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKwZPq0rdwpbljnKAs6B0QGlsas0EBG1A',
    appId: '1:811204575228:ios:a0991f5a297c27e2533c79',
    messagingSenderId: '811204575228',
    projectId: 'myapp-366c1',
    storageBucket: 'myapp-366c1.appspot.com',
    iosClientId: '811204575228-nijh99ejuobltsihnfk8d0hni4v70ndn.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
